### ISSUE TITLE
Import spreadsheets and csv files

### ISSUE THREAD

**Issue by ibrahimpenekli** [ibrahimpenekli/GameToolkit-Localization#1]
Generate localized text assets by importing **spreadsheet/csv** files automatically.

**Comment by yassir-ouali** [comment]
Any news about this enhancement ? would love to import JSON or XML files and generate the localizations automatically!

**Comment by ibrahimpenekli** [comment]
I will add this feature when I have spare time. No planned date at this time.

**Comment by ibrahimpenekli** [comment]
@yassir-ouali Can you send to me example JSON and XML files?

**Comment by TimNedvyga** [comment]
Hi, any news on this one?

**Comment by ibrahimpenekli** [comment]
You can import/export as .CSV under `Window -> GameToolkit -> Localization` menu. Detailed documentation will be ready soon.
