### ISSUE TITLE
Saving language

### ISSUE THREAD

**Issue by Wokarol** [ibrahimpenekli/GameToolkit-Localization#10]
What's the best way to save language setted by player while using this asset?

**Comment by Wokarol** [comment]
At this point I have this:
`using GameToolkit.Localization;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Wokarol
{
	public class LanguageSaver : MonoBehaviour
	{
		private const string languageKey = "LSaver_LanguageCode";
		[SerializeField] LocalizedText languageCodes;

		void Awake ()
		{

			if ((PlayerPrefs.HasKey(languageKey))) {
				Localization.Instance.CurrentLanguage = languageCodes.TypedLocaleItems.First(locale => locale.Value == PlayerPrefs.GetString(languageKey)).Language;
			} else {
				Localization.Instance.SetSystemLanguage();
				SaveValue();
			}

			Localization.Instance.LocaleChanged += (object sender, LocaleChangedEventArgs e) => {
				SaveValue();
			};
		}

		void SaveValue ()
		{
			PlayerPrefs.SetString(languageKey, languageCodes.Value);
			Debug.Log("Setted code to " + languageCodes.Value);
		}
	} 
}
`

**Comment by Wokarol** [comment]
At this point I have this:
`using GameToolkit.Localization;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Wokarol
{
	public class LanguageSaver : MonoBehaviour
	{
		private const string languageKey = "LSaver_LanguageCode";
		[SerializeField] LocalizedText languageCodes;

		void Awake ()
		{

			if ((PlayerPrefs.HasKey(languageKey))) {
				Localization.Instance.CurrentLanguage = languageCodes.TypedLocaleItems.First(locale => locale.Value == PlayerPrefs.GetString(languageKey)).Language;
			} else {
				Localization.Instance.SetSystemLanguage();
				SaveValue();
			}

			Localization.Instance.LocaleChanged += (object sender, LocaleChangedEventArgs e) => {
				SaveValue();
			};
		}

		void SaveValue ()
		{
			PlayerPrefs.SetString(languageKey, languageCodes.Value);
			Debug.Log("Setted code to " + languageCodes.Value);
		}
	} 
}`

**Comment by Wokarol** [comment]
At this point I have this:
```
using GameToolkit.Localization;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Wokarol
{
	public class LanguageSaver : MonoBehaviour
	{
		private const string languageKey = "LSaver_LanguageCode";
		[SerializeField] LocalizedText languageCodes;

		void Awake ()
		{

			if ((PlayerPrefs.HasKey(languageKey))) {
				Localization.Instance.CurrentLanguage = languageCodes.TypedLocaleItems.First(locale => locale.Value == PlayerPrefs.GetString(languageKey)).Language;
			} else {
				Localization.Instance.SetSystemLanguage();
				SaveValue();
			}

			Localization.Instance.LocaleChanged += (object sender, LocaleChangedEventArgs e) => {
				SaveValue();
			};
		}

		void SaveValue ()
		{
			PlayerPrefs.SetString(languageKey, languageCodes.Value);
			Debug.Log("Setted code to " + languageCodes.Value);
		}
	} 
}```

**Comment by ibrahimpenekli** [comment]
@Wokarol  Not tested, but i hope it will work:

```csharp


public class LanguageSaver : MonoBehaviour
{
    private const string languageKey = "LSaver_LanguageCode";
    
    private void Awake()
    {
        DontDestroyOnLoad(gameObject);

        if (PlayerPrefs.HasKey(languageKey))
        {
            Localization.Instance.CurrentLanguage = (SystemLanguage) PlayerPrefs.GetInt(languageKey);
        }

        Localization.Instance.LocaleChanged += Localization_OnLocaleChanged;
    }

    private static void Localization_OnLocaleChanged(object sender, LocaleChangedEventArgs e)
    {
            PlayerPrefs.SetInt(languageKey, (int) e.CurrentLanguage);
            PlayerPrefs.Save();
    }
}
```
