### ISSUE TITLE
Generic/unknown HTTP error

### ISSUE THREAD

**Issue by giveuplease** [ibrahimpenekli/GameToolkit-Localization#11]
Any idea why I got this error every time after I try to quickly translate missing locale in Localization Explorer?

**Comment by ibrahimpenekli** [comment]
Hi @giveuplease,

Did you find the reason of this issue?

**Comment by giveuplease** [comment]
Hi.
Yep. There were some problems with google billing system, but now all ok.
Thanks for the app

**Comment by ibrahimpenekli** [comment]
Glad to hear you fixed the problem. Enjoy with the plugin!
