### ISSUE TITLE
More Languages? ReadME?

### ISSUE THREAD

**Issue by danishsshaikh** [ibrahimpenekli/GameToolkit-Localization#13]
How about if we could add more languages to the asset? and update the readme with the current languages? : )

**Comment by ibrahimpenekli** [comment]
@danishsshaikh Do you mean the documentation language ?

**Comment by danishsshaikh** [comment]
> @danishsshaikh Do you mean the documentation language ?
Yeah, well i meant to ask is could we add more languages to the asset? Like I don't think if it supports Hindi or Marathi (Indian Languages) 
And, also update the documentation with how many current languages does the asset supports currently.

Thanks,
Dan

**Comment by ibrahimpenekli** [comment]
@danishsshaikh This system does the localization management only; it does not translates one language to another. It simply includes languages from Unity's [SystemLanguage](https://docs.unity3d.com/ScriptReference/SystemLanguage.html) enum. In the future, I might implement adding custom languages as well as built-in ones.

As you see, there are lots of languages in [SystemLanguage](https://docs.unity3d.com/ScriptReference/SystemLanguage.html) enum. Updating documentation for all languages is impossible at least for me :)

**Comment by danishsshaikh** [comment]
It all makes sense.
Thanks for replying back :)
