### ISSUE TITLE
Localization settings could not be found

### ISSUE THREAD

**Issue by gayanW** [ibrahimpenekli/GameToolkit-Localization#15]
In the documentation it says,

> Localization settings is created automatically when package is imported. Also you can manually create via

     Project Window -> GameToolkit -> Localization -> Localization Settings

I imported the 1.3 version from the asset store, but I can't seem to find such asset in my Assets directory. There's no such option in the `Window -> GameToolkit` menu bar either. This is tested in Unity 2018.4.11f1

**Comment by gayanW** [comment]
I was looking at the wrong place, which is the menu bar. But found that its in the right-click menu. I also found the LocalizationSettings file under `Assets ->  GameToolkit -> Localization -> Localization Settings`

Thank you for the excellent package, it is exactly what I needed.

**Comment by ibrahimpenekli** [comment]
Hi @gayanW,

I recommend you to install the package via Unity Package Manager instead of Asset Store. Asset Store version is old one and it will not be updated.

Enjoy the package!

**Comment by gayanW** [comment]
Thanks for the information.
Is the version mentioned in the URL correct:

    https://github.com/ibrahimpenekli/GameToolkit-Localization.git#2.2.0

Also is reinstalling from the package manager, with the existing classes possible. Or will I have to do a cleanup, before reinstalling through the package manager?

**Comment by ibrahimpenekli** [comment]
That's correct URL. You have to delete package folder that you downloaded from Asset Store to prevent duplicate scripts etc. 
But, you can keep created assets (LocalizedTexts, LocalizationSettings etc.) . They'll be updated automatically if needed.
