### ISSUE TITLE
'Newtonsoft' could not be found

### ISSUE THREAD

**Issue by mianumar** [ibrahimpenekli/GameToolkit-Localization#22]
It shows this error

Assets/Scripts/DataManager.cs(1,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

**Comment by mianumar** [comment]
I can fix this. please assign me to fix

**Comment by ibrahimpenekli** [comment]
This package doesn't have `DataManager` class, and doesn't use `Newtonsoft` at all. I guess it is your script.
