### ISSUE TITLE
Add clone button or feature to allow cloning of a localised asset type

### ISSUE THREAD

**Issue by oluwaseyeayinla** [ibrahimpenekli/GameToolkit-Localization#5]
Hi, I was wondering if you could add a clone button / feature to to the Localisation explorer so that its easy to clone a particular localised asset type with its predefined system language. This would make it breezy in adding more than one localisation asset when you have a bunch of them to fill out.

**Comment by ibrahimpenekli** [comment]
Now you can use `Ctrl+D` or `Edit->Duplicate` to duplicate selected items from Localization Explorer.
