### ISSUE TITLE
Localizing array of audio clips?

### ISSUE THREAD

**Issue by crmagicxxx** [ibrahimpenekli/GameToolkit-Localization#7]
Hi

In my game object, I have array of Audio Clips, that I then play in the code depending on the game state.
![screenshot 22](https://user-images.githubusercontent.com/1320690/43368056-2304a04a-9357-11e8-8ea0-11f19e737820.png)

Simply, I sometimes play infoSfxArray[0], sometimes infoSfxArray[1], etc... I tried many ways to localize such an array, but without a success. Do you have any idea how to implement this?

Thanks

**Comment by crmagicxxx** [comment]
Ok, I solved it by adding: `public LocalizedAudioClip[] localizedSfxArray;` to my script.
Assigned localized assets in the inspector and then instead of playing **infoSfxArray[0]** I play **localizedSfxArray[0].Value** 

If you have any better idea, let me know
Thanks for awesome asset, I just left a maximal review on the asset store 👍

**Comment by Dvarnrock** [comment]
Hello, Mr. Lazarevic!

I am sorry, I can hardly help you with this - I am a En-Ru text localization specialist, not a localization engineer. I could only help, if you need to translate some game or app texts from English to Russian or vice versa.

Best luck in finding the solution!

Cheers,
Pavel Kondrashov
________________________________

**Comment by ibrahimpenekli** [comment]
@crmagicxxx That seems OK. Also thanks for your review!
